jmp main
section main:
    mov r0,1
    mov r1,1
    push r1
    push r0
    bjmp fibnacci
    end
section fibnacci:
    ;取出参数
    pop r0
    pop r1
    add r0,r0,r1
    show r0
    push r0
    push r1
    mov r1,5000
    gt r0,r1
    cjmp return
    bjmp fibnacci
section return:
    ret