jmp main
section main:
    mov r0,1
    mov r1,1
    push r1
    push r0
    bjmp fibnacci
    end
section fibnacci:
    ;取出参数
    pop r0
    pop r1
    push lr
    add r0,r0,r1
    show r0
    mov r3,5000
    gt r0,r3
    cjmp return
    push r0
    push r1
    bjmp fibnacci
section return:
    pop lr
    ret